# Generated by Django 4.1 on 2023-08-05 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='level',
            field=models.IntegerField(choices=[(1, 'BEGINER'), (2, 'INTERMEDIATE'), (3, 'ADVANCED')], default=1),
        ),
    ]
